services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5051:5050"
    environment:
      - PORT=5050
      - JWT_SECRET=G@2#4fa5!E%P0KqwJH7^&8lbRvZu1DxsY9eTI+c3VN6o-@mLrBjW
      - MONGODB_URL=${MONGODB_URL}

  fontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5174:5173"

